language: java

env:
  global:
  - secure: KF4o6QO95xqTL1bwBOQQBP6bgJp7vaBRSZ4o8CrIK/8vSc6RAE+VGg4Q21UGjiyPJ+V3HR07qpOe9u/32ZtXIejTOg4UWjvOALw7IBczBF1xlUatVuKX3GGZOdSvnVaaNaxeM8rCJg80ixQ5/HZq+K8QiFCVYEkw0v6WEzJ7jMNb52e/Aptf7k2KvbZT+1loYXHMcqC37cm1SA3Ni4kdaBHkjs4YgOYnI3zCTwXDcZRYDNuqORS6VyMOA7sgiOyjMDhgYcgq6ypwHYj+JGpfKNrmdYAYFbHrBxzDdRWI9aKtRRN9/Al64/RpLjNucf3V+OaMI2zo9qMosdEsGe9posRnWA/Fsg1iiOYzGCZPTbziBkmFaF7AbB+Fyd0uXIJertVaB0hjEo7Mw72CGK75CZAbeorGtPG9Wk19GPWkj8L1BE1glB+FLwy5Qn6oCKaJsYhEp3mm+vBF/KHKIA1qGGTZH3HWYh9brOZgJYKrsBvwEcGQhtlPUd9yMVcbEw1sFLA77TffG+JgtTUQ062XjZEqOkpfOqoRUSq2KQU1eTismAkfwkFk1+bUgRaTYEyHlHsy9Tz7oRhYoGPtQ8r9TDPtmWuzQNzL6CGGxidaPOO1f+v6RTyQ0QLHhLvSXl2pTulNhM1ZlegcbXI9qPWjPg3MeNq/eaKWbrGiH+RzUGc=
  - secure: R6z1Hz4yZze73c8pNTM+lR4IXUH3yCzD0XuE1nTBT+BfLfy9jDtmquWSbDl2/AqST24N9KE7/FJhwC+0cy3zI17Rm0QXnGMazjU++UNB7M5RgMWLVh5+iBp6J3OWN++cJWOh9L9hu+LVTAnplIWppVFIT4fpR7rH+7+Ttfqoy1H+O80qbLIMaAYVth3uH2SkXWfIEogAITGj/yxejyfwNyQBNS8xI5745JzyTwISx2VJISMfBrT5rHuE/3/DPDVu3Dv+YB5ew8XXscnkg/pLgWsQEOtEr66GBFYcUVATn4XKhTofXB8YfCwm3Lou8cnfP1nOQo8FVbCN4uXKGahkPR98akEHq99pgBYezHJswQv3soRTtCLF6GZN4efkVgyRgGat2l0L59yAal1AWT2JisHu9fG6BE6HkzUNoBoT2OZ4l0HmkuS3grvLz1ZU0Lefyb1mQY3MHfzSH0JOhnWozLgNUjcNFZWaIHd2cP0mfCfpz2jtN8uTe/olXN+Rd/ZKyD3q1ZEnWwQhQcmYuT7P4rSlcW7+Ij2q+ovdE49BGhFfmob5JS1aPmU/C6fLyUcfMWiDY5aaNfnPmqv+QUV62kpDCu9RO40BJfMWbd1GRaTpWcY7QgoIJuLAUr9oRdRIA1eHYiGwfVgKAe44s9wbVn4y9jW0JTDW3KxjxoEgSwI=
  - secure: 2rW7umN0DBvDN6ZqbcNwwqeAKKGU1r0nv5i91/YLW7C07w6bKPllcx+Jsk9R6u56/0pUeq2zpO9c3y+XZbma55kYkw97KQLiFWaGFTafNC1dIBs/bimjsoDd7/F7m1KjublCO4ByGlyh0ldN3QYd56/Jmykk0PBIhnQrigxlMhVFwUd4Tbsx2n7ykKRmncfzFCH0aMDZ1JWdwvl/yrlKzJHQcdfpSVOqIELvIZHkKpTZrYTXKHVyb7DAn2SzdIn75tiZHDif1sj/XSiU8dk7jSzulrEjajcoOOe5uUOoJG9V32GaJJklVUrh6fx1Jy17Opzo2lrtpmCItOQfqyjAjzWTS03QprW8vr3xLNMH78C1IH/7GEu1yidFrO2FgsnZokPHiyUJDosl7ifp9xv6DuvKkLHu6o0yd3XImMosdW4q/KGswtLcLdlX9uBptz1e7gx8zmgeOgGWI9/vihDr8XYwZI5kGcE9m82TYLA0W/41jKkBHeWdLxyJqocHJ7qPs5MHrJyZ0arrJHdznqh1BgHDAIA326Kq8IxPPEGdjdATanmUeNIOdfUgVPasKgiLQR4yW4Euuov3LNjwtpNToSQ5oQB8mrc3PZkShb+OK64Xm+c7PHqXT28kRWJUIm/LxF85i3xs5vOXC9fLd1r0+YzTK9ntYyAgm/kndwP4Ggw=
install: true

addons:
  sonarcloud:
    organization: "kentico-github"
    token:
      secure: "j2lyZTrsGvCSHJefMQLqKrQ5iicdUaJY0/7RLD2jMCpeXMhJa8fTvus3QPvjelw/uNeIUBAAPWrBjtkpgUDVlTxc+iz3+an6TvMBuabas81J7CSCEG7XBA27MHRCKtlmYa5hXL+FQcTDIYzNObM8722RPxuNT7Yx+Oq+GMNF2m2DCTzal4Fez7Ql2tDJIsxXmcfFQJeX0huBiEpCu/oDxf04IkleQE0Z56U+EnuGIvrffDkGYaCU/41WA5ZDfDqVBazE1fueaZs0yCPLLrAZX6Lm0uEykw0nvi6HjbOVTw2P0IKEsgKqJQn3m5K7f/nCprHB9kCjtFIyOPqv681OUvatXhbZ+/NE8BPxXhzZw0KIaDFIieQFdKd1KyxR3wFAIfNoLYZCRi0uUsxFIIgzrBrL5v9i2SvIPxaxxtwxsVQnEKHXLwJzbwhj6HIxWwI1WwaGXLB6+qCATTvacCRtDoZrG47/06haiVKWoLeO6epTEkb1GiEw0H84XFspZHVIGiUBrwTv6j0t4UPtXzipjQHofLpswAj+3KQbZ3NjfPlqcTI6KNgpiJMR3fBm141GihdNgVldMU42IG0kfbztlqGONVdU1udPQF/lNGHFuNStvJs1AWA1MM2wjT2ope6Q7l3l90ZcsmfiU1bjafE7RrU/rDX9+5FSId7Qj0/kS1c="

script:
  - ./gradlew sonarqube
  - ".travis/upload_nexus.sh"

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of gradle deploy
  - rm -f  $HOME/.gradle/caches/modules-2/modules2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.sonar/cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper

before_install:
- openssl aes-256-cbc -K $encrypted_604254be91e3_key -iv $encrypted_604254be91e3_iv
  -in signing.gpg.enc -out signing.gpg -d

